"""baseline - h3_heatmap ve reports tablolari (risk kanallari dahil)

Revision ID: 4ba90bcb6804
Revises: 
Create Date: 2026-07-12 18:23:50.289138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '4ba90bcb6804'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A fresh Supabase project ships the PostGIS package but does not enable the
    # extension. Keep the extension outside ``public`` as recommended by
    # Supabase, then expose its types for the unqualified GeoAlchemy DDL emitted
    # below. ``IF NOT EXISTS`` also preserves local PostGIS images that install
    # the extension in ``public`` ahead of time.
    op.execute("CREATE SCHEMA IF NOT EXISTS extensions")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA extensions")
    op.execute('SET LOCAL search_path TO "$user", public, extensions')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('h3_heatmap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('h3_index', sa.String(length=15), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('risk_historical', sa.Float(), nullable=True),
    sa.Column('risk_live', sa.Float(), nullable=True),
    sa.Column('risk_social', sa.Float(), nullable=True),
    sa.Column('total_risk', sa.Float(), nullable=True),
    sa.Column('domestic', sa.Boolean(), nullable=True),
    sa.Column('location_description', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('extra_features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_h3_heatmap_location', 'h3_heatmap', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_h3_heatmap_date'), 'h3_heatmap', ['date'], unique=False)
    op.create_index(op.f('ix_h3_heatmap_h3_index'), 'h3_heatmap', ['h3_index'], unique=False)
    op.create_index(op.f('ix_h3_heatmap_id'), 'h3_heatmap', ['id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.execute("DROP INDEX IF EXISTS idx_reports_location;")
    op.drop_table('reports')
    op.drop_index(op.f('ix_h3_heatmap_id'), table_name='h3_heatmap')
    op.drop_index(op.f('ix_h3_heatmap_h3_index'), table_name='h3_heatmap')
    op.drop_index(op.f('ix_h3_heatmap_date'), table_name='h3_heatmap')
    op.execute("DROP INDEX IF EXISTS idx_h3_heatmap_location;")
    op.drop_table('h3_heatmap')
    # ### end Alembic commands ###
